### ISSUE TITLE
We sometimes seem to be running jbuilder in interactive mode

### ISSUE THREAD

**Issue by yminsky** [realworldocaml/book#2919] opened 2018-03-23 21:10 UTC
As the following results show:

![image](https://user-images.githubusercontent.com/715302/37853417-04272e62-2ebd-11e8-9abb-f08ea1ee1819.png)

**Comment by samoht** [comment] 2018-06-01 14:44
I cannot reproduce the issue anymore, so closing.

**Closed by samoht** 2018-06-01 14:44 UTC
